import BaseSchema from '@ioc:Adonis/Lucid/Schema'

export default class extends BaseSchema {
  protected tableName = 'tasks'

  public async up () {
    this.schema.createTable(this.tableName, (table) => {
      table.text('_id')
      table.text('status')
      table.text('team_id')
      table.text('order_id')
      table.text('merchant_id')
      table.text('items')
      table.text('pickup_pickup_timestamp')
      table.text('pickup_name')
      table.text('pickup_contact')
      table.text('pickup_location_type')
      table.text('pickup_location_coordinates')
      table.text('pickup_address_full_address')
      table.text('pickup_address_building')
      table.text('pickup_address_area')
      table.text('pickup_address_landmark')
      table.text('pickup_address_city')
      table.text('pickup_address_country_code')
      table.text('pickup_payment_amount')
      table.text('pickup_payment_currency_code')
      table.text('pickup_payment_amount_formatted')
      table.text('pickup_tracking_url')
      table.text('drop_drop_timestamp')
      table.text('drop_name')
      table.text('drop_contact')
      table.text('drop_location_type')
      table.text('drop_location_coordinates')
      table.text('drop_address_full_address')
      table.text('drop_address_building')
      table.text('drop_address_area')
      table.text('drop_address_landmark')
      table.text('drop_address_city')
      table.text('drop_address_country_code')
      table.text('drop_payment_amount')
      table.text('drop_payment_currency_code')
      table.text('drop_payment_amount_formatted')
      table.text('drop_tracking_url')
      table.text('task_comment')
      table.text('task_lock')
      table.text('task_lock_job_dispatched')
      table.text('auto_assigned')
      table.text('auto_assigning')
      table.text('distance_calculation_method')
      table.text('distance_calculation_start_point')
      table.text('time_calculation_start_point')
      table.text('distance_unit')
      table.text('is_task_batching_enabled')
      table.text('is_multiple_merchant_task_batching_enabled')
      table.text('task_auto_assign_retries_left')
      table.text('updated_at')
      table.text('created_at')
      table.text('status_history')
      table.text('task_tracking_url')
      table.text('auto_assign_job_failed')
      table.text('agent_id')
      table.text('force_assigned')
      table.text('distance')
      table.text('task_id')
      table.text('distance_symbol')
    })
  }

  public async down () {
    this.schema.dropTable(this.tableName)
  }
}
