export default (data: any) => {
  const payload = {
    event: data.event,
    payload__id: data.payload._id,
    payload_tenant_id: data.payload.tenant_id,
    payload_merchant_id: data.payload.merchant.id,
    payload_user_id: data.payload.user.id,
    payload_user_tenant_id: data.payload.user.tenant_id,
    payload_user_first_name: data.payload.user.first_name,
    payload_user_last_name: data.payload.user.last_name,
    payload_user_mobile: data.payload.user.mobile,
    payload_user_email: data.payload.user.email,
    payload_user_email_verified_at: data.payload.user.email_verified_at,
    payload_user_country_code: data.payload.user.country_code,
    payload_user_is_new_user: data.payload.user.is_new_user,
    payload_user_status: data.payload.user.status,
    payload_user_created_at: data.payload.user.created_at,
    payload_user_updated_at: data.payload.user.updated_at,
    payload_user_deleted_at: data.payload.user.deleted_at,
    payload_user_tenants_limit: data.payload.user.tenants_limit,
    payload_user_full_name: data.payload.user.full_name,
    payload_user_status_name: data.payload.user.status_name,
    payload_user_roles: data.payload.user.roles,
    payload_user_permissions: data.payload.user.permissions,
    payload_user_admin_tenants: data.payload.user.admin_tenants,
    payload_user_merchant_users: data.payload.user.merchant_users,
    payload_user_social_accounts: data.payload.user.social_accounts,
    payload_user_redirect_panel: data.payload.user.redirect_panel,
    payload_cart__id: data.payload.cart._id,
    payload_cart_tenant_id: data.payload.cart.tenant_id,
    payload_cart_cart_items: data.payload.cart.cart_items,
    payload_cart_total_items: data.payload.cart.total_items,
    payload_cart_total_amount: data.payload.cart.total_amount,
    payload_cart_is_updated: data.payload.cart.is_updated,
    payload_cart_user_id: data.payload.cart.user_id,
    payload_cart_updated_at: data.payload.cart.updated_at,
    payload_cart_created_at: data.payload.cart.created_at,
    payload_cart_raw_calculation: data.payload.cart.raw_calculation,
    payload_cart_sub_total_amount: data.payload.cart.sub_total_amount,
    payload_cart_message: data.payload.cart.message,
    payload_cart_custom_charges: data.payload.cart.custom_charges,
    payload_cart_delivery_fee: data.payload.cart.delivery_fee,
    payload_cart_delivery_tax: data.payload.cart.delivery_tax,
    payload_cart_is_delivery_tax_applied: data.payload.cart.is_delivery_tax_applied,
    payload_cart_tax: data.payload.cart.tax,
    payload_cart_cart_id: data.payload.cart.cart_id,
    payload_cart_total_amount_formatted: data.payload.cart.total_amount_formatted,
    payload_cart_sub_total_amount_formatted: data.payload.cart.sub_total_amount_formatted,
    payload_cart_discount_amount_formatted: data.payload.cart.discount_amount_formatted,
    payload_cart_tax_formatted: data.payload.cart.tax_formatted,
    payload_cart_delivery_fee_formatted: data.payload.cart.delivery_fee_formatted,
    payload_cart_delivery_tax_formatted: data.payload.cart.delivery_tax_formatted,
    payload_cart_currency_setting: data.payload.cart.currency_setting,
    payload_merchant__id: data.payload.merchant._id,
    payload_merchant_tenant_id: data.payload.merchant.tenant_id,
    payload_merchant_phone: data.payload.merchant.phone,
    payload_merchant_language_translation: data.payload.merchant.language_translation,
    payload_merchant_email: data.payload.merchant.email,
    payload_merchant_address: data.payload.merchant.address,
    payload_merchant_delivery_by: data.payload.merchant.delivery_by,
    payload_merchant_accepted_order_types: data.payload.merchant.accepted_order_types,
    payload_merchant_merchant_package_id: data.payload.merchant.merchant_package_id,
    payload_merchant_commission: data.payload.merchant.commission,
    payload_merchant_group_ids: data.payload.merchant.group_ids,
    payload_merchant_merchant_category_ids: data.payload.merchant.merchant_category_ids,
    payload_merchant_status: data.payload.merchant.status,
    payload_merchant_delivery_amount: data.payload.merchant.delivery_amount,
    payload_merchant_min_order_amount: data.payload.merchant.min_order_amount,
    payload_merchant_average_rating: data.payload.merchant.average_rating,
    payload_merchant_is_accepting_orders: data.payload.merchant.is_accepting_orders,
    payload_merchant_is_open: data.payload.merchant.is_open,
    payload_merchant_merchant_address_location: data.payload.merchant.merchant_address_location,
    payload_merchant_merchant_id: data.payload.merchant.merchant_id,
    payload_merchant_slug: data.payload.merchant.slug,
    payload_merchant_images: data.payload.merchant.images,
    payload_merchant_delivery_location_type: data.payload.merchant.delivery_location_type,
    payload_merchant_delivery_radius: data.payload.merchant.delivery_radius,
    payload_merchant_delivery_radius_meters: data.payload.merchant.delivery_radius_meters,
    payload_merchant_delivery_radius_unit: data.payload.merchant.delivery_radius_unit,
    payload_merchant_merchant_location: data.payload.merchant.merchant_location,
    payload_merchant_comment: data.payload.merchant.comment,
    payload_merchant_merchant_categories: data.payload.merchant.merchant_categories,
    payload_merchant_name: data.payload.merchant.name,
    payload_merchant_language_translate_columns: data.payload.merchant.language_translate_columns,
    payload_payment_mode_id: data.payload.payment_mode_id,
    payload_payment_mode_tenant_id: data.payload.payment_mode.tenant_id,
    payload_payment_mode_payment_mode_id: data.payload.payment_mode.payment_mode.id,
    payload_payment_mode_language_translation: data.payload.payment_mode.language_translation,
    payload_payment_mode_settings_value: data.payload.payment_mode.settings_value,
    payload_payment_mode_active: data.payload.payment_mode.active,
    payload_payment_mode_alias: data.payload.payment_mode.alias,
    payload_payment_mode_payment_mode: data.payload.payment_mode.payment_mode,
    payload_order_type: data.payload.order_type,
    payload_review: data.payload.review,
    payload_order_status: data.payload.order_status,
    payload_order_amount: data.payload.order_amount,
    payload_order_amount_formatted: data.payload.order_amount_formatted,
    payload_currency_code: data.payload.currency.code,
    payload_currency_symbol_direction: data.payload.currency.symbol_direction,
    payload_currency_symbol_type: data.payload.currency.symbol_type,
    payload_currency_symbol: data.payload.currency.symbol,
    payload_currency_symbol_native: data.payload.currency.symbol_native,
    payload_delivery_timestamp_human_date: data.payload.delivery_timestamp_human.date,
    payload_delivery_timestamp_human_time: data.payload.delivery_timestamp_human.time,
    payload_delivery_timestamp_human_local_date: data.payload.delivery_timestamp_human.local_date,
    payload_delivery_timestamp_human_local_time: data.payload.delivery_timestamp_human.local_time,
    payload_delivery_timestamp_unix: data.payload.delivery_timestamp_unix,
    payload_is_scheduled: data.payload.is_scheduled,
    payload_is_user_first_order: data.payload.is_user_first_order,
    payload_push_auth_token: data.payload.push_auth_token,
    payload_meta_custom_form: data.payload.meta.custom_form,
    payload_ip: data.payload.ip,
    payload_device: data.payload.device,
    payload_delivery_address__id: data.payload.delivery_address._id,
    payload_delivery_address_tenant_id: data.payload.delivery_address.tenant_id,
    payload_delivery_address_user_id: data.payload.delivery_address.user_id,
    payload_delivery_address_address_type: data.payload.delivery_address.address_type,
    payload_delivery_address_location_lat_lon: data.payload.delivery_address.location_lat_lon,
    payload_delivery_address_address: data.payload.delivery_address.address,
    payload_delivery_address_building: data.payload.delivery_address.building,
    payload_delivery_address_area: data.payload.delivery_address.area,
    payload_delivery_address_landmark: data.payload.delivery_address.landmark,
    payload_delivery_address_city: data.payload.delivery_address.city,
    payload_delivery_address_region: data.payload.delivery_address.region,
    payload_delivery_address_zip_code: data.payload.delivery_address.zip_code,
    payload_delivery_address_country: data.payload.delivery_address.country,
    payload_delivery_address_country_code: data.payload.delivery_address.country_code,
    payload_delivery_address_updated_at: data.payload.delivery_address.updated_at,
    payload_delivery_address_created_at: data.payload.delivery_address.created_at,
    payload_order_id: data.payload.order_id,
    payload_created_timestamp_unix: data.payload.created_timestamp_unix,
    payload_updated_at: data.payload.updated_at,
    payload_created_at: data.payload.created_at,
    payload_order_status_history: data.payload.order_status_history,
    payload_order_uuid: data.payload.order_uuid,
    payload_local_created_at: data.payload.local_created_at,
    payload_order_type_label: data.payload.order_type_label,
    payload_allowed_update_order_status_merchant: data.payload.allowed_update_order_status.merchant,
    payload_mq_queue: data.payload.mq_queue,
    payload_binding_key: data.payload.binding_key,
  }

  for (const key in payload) {
    const value = payload[key]

    if (typeof value === 'string' || value instanceof String) {
      continue
    }

    payload[key] = JSON.stringify(value)
  }

  return payload
}
